TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Nezaniel.Repertory': TRUE
    nodeTypes:
      groups:
        repertory:
          position: 'after general'
          label: 'Repertory'
  Flow:
    session:
      # We don't want our session to expire since gig data is stored there
      inactivityTimeout: 0